FROM python:3.9-slim
WORKDIR /app

RUN mkdir -p /root/.config/pip && \
    echo "[global]" > /root/.config/pip/pip.conf && \
    echo "index-url = https://pypi.org/simple" >> /root/.config/pip/pip.conf && \
    echo "trusted-host = pypi.org files.pythonhosted.org" >> /root/.config/pip/pip.conf && \
    echo "timeout = 60" >> /root/.config/pip/pip.conf && \
    echo "retries = 5" >> /root/.config/pip/pip.conf

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
